exclude = [
    "venv",
    ".git",
    ".ruff_cache",
    ".vscode"
]
line-length = 250
indent-width = 4
target-version = "py39"

[lint]
select = [
  "F",
  "E",
  "W",
  "C",
  "B",
  "I",
  "YTT",
  "ASYNC",
  "RUF",
  "AIR",
  "NPY",
  "C4",
  "T10",
  "EXE",
  "ISC",
  "ICN",
  "RSE",
  "TCH",
  "TID",
  "INT",
  "PLE",
]
ignore = [
  "B006",   # Do not use mutable data structures for argument defaults
  "B008",   # Do not perform function call in argument defaults
  "C408",   # Unnecessary `dict` call
  "I001",   # Import block is un-sorted or un-formatted
  "E402",   # Module level import not at top of file
  "E501",   # Line too long
  "E721",   # Do not compare types, use `isinstance()`
  "E731",   # Do not assign a `lambda` expression, use a `def`
  "E741",   # Ambiguous variable name
  "F401",   # Imported by unused
  "NPY002", # replace legacy random
  "RUF005", # Consider iterable unpacking
  "RUF010", # Use explicit conversion flag
  "RUF012", # Mutable class attributes
  "RUF013", # PEP 484 prohibits implicit `Optional`
  "RUF015", # Prefer `next(...)` over single element slice
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false

[lint.mccabe]
max-complexity = 150
